name: the_fuel_war
main: the_fuel_war\Main
version: "1.0"
api: [3.0.0, 4.0.0]
author: "suinua"

commands:
  map:
    usage: "/map"
    description: "map"
    permission: op
  gamelist:
    usage: "/gamelist"
    description: "open game list"
    permission: op
  room:
    usage: "/room"
    description: "open waiting room list"
    permission: op
  board:
    usage: "/board"
    description: "summon board"
    permission: op
  computer:
    usage: "/computer"
    description: "summon computer"
    permission: op
  removenpc:
    usage: "/removenpc"
    description: "get RemoveNpcItem"
    permission: op
  worldlist:
    usage: "/worldlist"
    description: "open WorldListForm"
    permission: op
